### ISSUE TITLE
No ExecutionEngine?

### ISSUE THREAD

**Issue by jeb2239** [mrecachinas/Kaleidoscope-Language#1]
I noticed that in toplevel.ml

 ```ocaml
let result = ExecutionEngine.run_function the_function [||]
```

There is a reference to a module ExecutionEngine. I can't compile the ocaml example because this module is unbound.

I am compiling like this
```
ocamlbuild -use-ocamlfind toy.byte -package llvm -package camlp4 -package llvm.executionengine
```

There is no executionengine.ml in the example.

**Comment by mrecachinas** [comment]
@jeb2239 -- sorry, I had been following the [LLVM Kaleodoscope (OCaml) tutorial](http://llvm.org/docs/tutorial/OCamlLangImpl1.html) and stopped midway, so it's by no means done and I recall it not compiling when I stopped.

I do intend to complete the tutorial at some point, but you should check it out and follow that instead of my (incomplete) code.

**Comment by jeb2239** [comment]
oh no problem, thank you.
